grafana:
  admin:
    existingSecret: grafana-admin-credentials
    userKey: admin-user
    passwordKey: admin-password
  ingress:
    enabled: false
  sidecar:
    dashboards:
      enabled: true
      label: grafana_dashboard
      searchNamespace: ALL
      folder: /var/lib/grafana/dashboards/trafiq
    datasources:
      enabled: true
