version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: trafiq_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin1234
      POSTGRES_DB: trafiq_db
    ports:
      - '5432:5432'
    volumes:
      - trafiq_pgdata:/var/lib/postgresql/data

  mailhog:
    image: mailhog/mailhog:latest
    container_name: trafiq_mailhog
    restart: unless-stopped
    ports:
      - '1025:1025'   # SMTP
      - '8025:8025'   # Web UI

volumes:
  trafiq_pgdata:
